fantusya/petly

- src/helpers/validationSchemas/loginSchema.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/routeFormLoginRegister.jsx
Привет, набросал предварительно разметку формы регистрации.
> Предварительная разметка

- src/components/NavigationContainer/NavigationContainer.jsx
В хедере добавил ссылку на гугл аутентификации
> adds a link for google auth

- src/components/App.jsx
- src/helpers/validationSchemas/index.js
- src/pages/LoginPage/LoginPage.jsx
- src/pages/LoginPage/LoginPage.styled.jsx
Насть, не дописал еще стили, хоту редакс стянуть что б все было.
> стили логин, недописанные

- src/pages/NoticesPage/NoticesPage.jsx
- src/pages/NoticesPage/NoticesPage.styled.jsx
> Add the bone of NoticePage

- src/components/App.jsx
- src/components/FriendsList/FriendsList.jsx
- src/components/FriendsList/FriendsList.styled.jsx
- src/components/FriendsList/index.js
- src/components/FriendsPopUp/FriendsPopUp.jsx
- src/components/FriendsPopUp/index.js
- src/pages/OurFriendsPage/OurFriendsPage.jsx
- src/pages/OurFriendsPage/OurFriendsPage.styled.jsx
На зображення пока поставив свою заглушку, то тимчасово. Завтра сяду допрацьовувати.
> Our Friends Page

- src/pages/NoticesPage/NoticesPage.jsx
- src/pages/NoticesPage/NoticesPage.styled.jsx
> Local change

- src/components/PetForm/PetForm.jsx
- src/components/PetForm/Steps.jsx
- src/helpers/validationSchemas/validationPetSchema.jsx
поля з датою і додаванням фото поки закоментувала, з ними ще треба працювати
> form to add pet

- src/components/PetCard/PetCard.jsx
- src/components/PetCard/PetCard.styled.jsx
- src/components/PetsData/PetsData.jsx
- src/components/PetsData/PetsData.styled.jsx
- src/components/PetsList/PetsList.jsx
- src/components/PetsList/PetsList.styled.jsx
> styles to Pets

- src/components/FriendsList/FriendsList.jsx
- src/components/FriendsList/FriendsList.styled.jsx
- src/pages/OurFriendsPage/OurFriendsPage.jsx
- src/pages/OurFriendsPage/OurFriendsPage.styled.jsx
> Our friends page(adaptive styles)

- package-lock.json
- package.json
- src/components/AddNoticeButton/AddNoticeButton.jsx
- src/components/AddNoticeButton/AddNoticeButton.styled.jsx
- src/components/AddNoticeModal/AddNoticeModal.jsx
- src/components/NoticesCategoriesNav/NoticesCategoriesNav.jsx
- src/components/NoticesCategoriesNav/NoticesCategoriesNav.styled.jsx
- src/index.js
> Add fixed AddNoticeBtn

- src/pages/LoginPage/LoginPage.jsx
- src/pages/LoginPage/LoginPage.styled.jsx
- src/pages/authFormStyle.styled.jsx
Исправил стили кнопки гугл логин, чтобы была адаптивной
> fixes responsive style of login google button

- src/components/AddNoticeButton/AddNoticeButton.jsx
- src/components/AddNoticeButton/AddNoticeButton.styled.jsx
Змінив react-use на react-media
> Add changed Component with react-media

- src/pages/HomePage/HomePage.styled.jsx
> initial commit

- src/pages/NewsPage/NewsPage.jsx
Виправив фільтрування (не змінюйте назви функцій чи перемінних в загальному коді без попередження) переробив сортування (відбувався збій через NaN)
підправив підказки (поки вивід в консоль)
> fixed sort & filter

- src/pages/NewsPage/NewsPage.jsx
при правці формули пропустив знак,- виправлено
> fixed "<" to "-"

- src/components/Modal/Modal.styled.jsx
- src/components/NoticesCategoriesNav/NoticesCategoriesNav.jsx
> Add start changes

- src/components/PetForm/PetForm.jsx
- src/components/PetForm/PetForm.styled.jsx
- src/components/PetForm/Steps.jsx
- src/components/PetsData/PetsData.jsx
- src/helpers/validationSchemas/validationPetSchema.jsx
стилі поля додаванння фото ще поправлю
превью фото в коді поки закоментувала, воно мені щось матюкалось
> addPet to collection

- src/components/PetForm/PetForm.styled.jsx
- src/components/PetForm/Steps.jsx
> fix styled form

- src/pages/HomePage/HomePage.jsx
- src/pages/HomePage/HomePage.styled.jsx
> fix 3333333

- src/components/UserData/UserPhoto/UserPhoto.jsx
- src/components/UserDataItem/UserBirthday/UserBirthday.jsx
- src/components/UserDataItem/UserCity/UserCity.jsx
- src/components/UserDataItem/UserEmail/UserEmail.jsx
- src/components/UserDataItem/UserName/UserName.jsx
- src/components/UserDataItem/UserPhone/UserPhone.jsx
> adds user page translate

- src/components/FriendsList/FriendsList.styled.jsx
- src/i18n.js
Прибрав зайві дві крапки, та трохи підправив стилі
> Our Friends Page(upd)

- package-lock.json
- src/components/AddNoticeModal/AddNoticeModal.jsx
- src/components/AddNoticeModal/AddNoticeModal.styled.jsx
- src/components/AddNoticeModal/Steps/StepOne.jsx
- src/components/AddNoticeModal/Steps/StepTwo.jsx
- src/components/NoticeModal/NoticeModal.styled.jsx
- src/components/commonComponents/ModalButtons.styled.jsx
- src/helpers/addNoticeCustomField/noticeInput.js
Додаю попередньо стилі, і ще вечором ними займусь
> Add Style for NoticeModal

- src/components/AddNoticeModal/Steps/StepOne.jsx
Задача від ментора у Slack під номером 16
> Add fix metor task #16 (in Slack)

- src/components/PetForm/Steps.jsx
- src/components/PetsList/PetsList.jsx
- src/components/PetsList/PetsList.styled.jsx
поміняла місцями кнопки до зауваження Іветти, зробила заглушку зі стилями
> заглушка для петс

- src/components/UserData/UserPhoto/UserPhoto.jsx
- src/components/UserDataItem/UserBirthday/UserBirthday.jsx
- src/components/UserDataItem/UserCity/UserCity.jsx
- src/components/UserDataItem/UserEmail/UserEmail.jsx
- src/components/UserDataItem/UserName/UserName.jsx
- src/components/UserDataItem/UserPhone/UserPhone.jsx
- src/helpers/getFormatedDate.js
- src/helpers/validationSchemas/userValidationSchema.jsx
add validation, add avatar bagfix, add default birth date, add a condition if there are no changes in the input
> add bagfix

- src/components/Logout/Logout.jsx
- src/components/UserData/UserData.jsx
- src/components/UserData/UserData.styled.jsx
- src/components/UserData/UserModal/UserModal.jsx
- src/components/UserData/UserModal/UserModal.styled.jsx
- src/components/UserData/UserModal/index.js
- src/components/UserData/UserPhoto/UserPhoto.jsx
- src/keyframes/index.js
add animation for section, add user modal for logout
> Feature userdata
